- id: flake8-pytest-style
  name: flake8-pytest-style
  description: Check common style issues or inconsistencies with pytest-based tests
  entry: flake8
  language: python
  types: [python]
  additional_dependencies: [flake8>=7.3.0]
  require_serial: true
